### PR TITLE
Use better error display

### PR DESCRIPTION
**Pull request by zbraniecki**
This is a port of error display code from rust. I think it gives us a better quality output already, but I'm pretty sure we can clean it up more.

Let me know what you think @stasm .

### CODE REVIEW

**Comment by zbraniecki** [comment]
sgtm!

**Comment by stasm** [comment]
Having read https://blog.rust-lang.org/2016/08/10/Shape-of-errors-to-come.html and http://www.jonathanturner.org/2016/08/helping-out-with-rust-errors.html I changed my thinking a bit. I described it in https://github.com/projectfluent/fluent/wiki/Error-reporting.

**Comment by eemeli** [comment]
@zbraniecki @stasm Is this still relevant to keep around, or is this PR as outdated as it appears to be?

**Comment by zbraniecki** [comment]
I'm ok closing it. I'd love to see some equivalent of annotate-snippets-rs in JS and put it to use, but I don't think this is actionable right now and we'll likely only start looking into it with tooling for MF2.0

**Comment by stasm** [comment]
Closing sounds good to me, thanks.

**Pull request closed without merging**
