### PR TITLE
Use Object.prototype.hasOwnProperty.call

### LINKED ISSUE #428: Cannot pass variable named `hasOwnProperty`
```ini
test-without-var = OK
test-with-var = {$var}
```

```json
{
    "var": "OK",
    "hasOwnProperty": 0
}
```

The first message correctly formats to `OK`, but the second one produces `{???}`. At least [this][buggy-line] condition should be changed to `Object.prototype.hasOwnProperty.call(scope.args, name)`; there may be other similiar problems somewhere.

_JavaScript is a wonderful language, isn’t it?_

[buggy-line]: https://github.com/projectfluent/fluent.js/blob/eb26c7665/fluent-bundle/src/resolver.js#L118

### PR DESCRIPTION
**Pull request by stasm**
Fix #428.

### CODE REVIEW

**Comment by Pike** [comment]
I like the idea, I'm wondering if we should use `Object.create(null)` for the `scope.params`?

**Comment by stasm** [comment]
I've been thinking about this, and the same about named arguments to functions. But in the end, the `hasOwnProperty` check makes the distinction between `{}` and `Object.create(null)` irrelevant, I think?

**Comment by Pike** [comment]
Probably.

**Comment by stasm** [comment]
I used `Object.create(null)` for named parameters after all. It can't hurt and might actually help when writing custom functions.

**Pull request merged**
