### PR TITLE
Added option to FluentBundle to allow overriding messages and terms with a new value

### PR DESCRIPTION
**Pull request by marcselman**
By allowing overrides I can dynamically load new messages when needed.

### CODE REVIEW

**Comment by stasm** [comment]
Thank you for the PR, @marcselman! Can you describe in a bit more detail in which situations this could be useful? When updated translations are available, I usually recommend creating a new bundle. This is similar in effect to the scenario when the language preference changes dynamically.

**Comment by marcselman** [comment]
I have an app that I deploy to different domains (projects). Most of the strings are the same for each domain but on some I want to change a piece of text.

I have setup my .ftl files something like this:
```
fluent\en-US.ftl
fluent\nl-NL.ftl
fluent\project-group1\en-US.ftl
fluent\project-group1\nl-NL.ftl
fluent\project-group1\project1\en-US.ftl
fluent\project-group1\project1\nl-NL.ftl
fluent\project-group1\project2\en-US.ftl
fluent\project-group1\project2\nl-NL.ftl
```

The files in `fluent` are the base texts that are shared by all the projects
The project-group folders contain strings that are specific for that specific group of projects
The project folders contain specific strings that are only needed for that project

If for example I have 10 projects that share the same string I would put that in `fluent\en-US.ftl`.
But I want a different string for one specific project I would put that in `fluent\project-group1\project1\en-US.ftl`. Right now that gives the console error and does not override the string.
The only way to work around it is to move the string to all the separate project files so than I have 9 duplicate copies and one different. That makes it a lot of work to maintain.

**Comment by marcselman** [comment]
@stasm Have you had some time to look at the code? It's a minimal change.

**Comment by stasm** [comment]
Hi @marcselman, thanks again for the PR and for explaining your use-case. I've talked about this with @Pike and he suggested that the `addResource` and `addMessages` methods might be better places to pass this option, rather than setting it bundle-wide once. This would allow greater granularity in controlling when to allow overrides and when to forbid them. This could be used to discover duplicate message definitions across resources which are not meant as overrides, but rather base resources to be overridden. 

What do you think? Would you mind amending the PR to reflect this feedback? Ideally, we'd also add a few tests before landing it. Let me know what you think. Thanks!

**Comment by marcselman** [comment]
Hi @stasm, I've updated the PR with the suggested changes. I hope it can be merged into the library so I can use it in my project.

**Comment by stasm** [comment]
Thanks, @marcselman, nice work. Would also mind adding a simple test for this change?

I haven't run it, but something like this should do the trick. I would put it in [`fluent/test/context_test.js`](https://github.com/projectfluent/fluent.js/blob/master/fluent/test/context_test.js) around line 90. Or let me know and I'll be happy to do it before merging this PR.

```js
  suite('allowOverrides', function(){
    suiteSetup(function() {
      bundle = new FluentBundle('en-US', { useIsolating: false });
      let resource1 = FluentResource.fromString('key = Foo');
      let resource2 = FluentResource.fromString('key = Bar');
      bundle.addResource(resource1);
    });

    test('allowOverrides is false', function() {
      let errors = bundle.addResource(resource2);
      assert.equal(errors.length, 1);
      let msg = bundle.getMessage('key');
      assert.equal(bundle.format(msg), 'Foo');
    });

    test('allowOverrides is true', function() {
      let errors = bundle.addResource(resource2, {allowOverrides: true});
      assert.equal(errors.length, 0);
      let msg = bundle.getMessage('key');
      assert.equal(bundle.format(msg), 'Bar');
    });
});
```

**Comment by marcselman** [comment]
@stasm Done. I've also added an extra `allowOverrides` test to the `addMessages` suite.

**Comment by stasm** [comment]
Nice, thanks again! I'll publish a new version of `fluent` later today, or tomorrow.

**Comment by marcselman** [comment]
🙌🏻 awesome!

**Comment by stasm** [comment]
I published `fluent` 0.11.0 on npm today. Thank you, @marcselman, for the contribution!

**Pull request merged**
