### PR TITLE
Reference multiline patterns

### PR DESCRIPTION
**Pull request by zbraniecki**
Fixes the multiline inlines in #239.

### CODE REVIEW

**Comment by zbraniecki** [comment]
This is on top of  #232 so really only the last commit should be reviewed.

**Comment by Pike** [comment]
As I said on IRC, I think this is an issue in the reference parser more than an actual spec part. At least in the scope of 0.6.

**Comment by zbraniecki** [comment]
Rebased on top of syntax-0.6 to simplify assessing the code.

**Comment by stasm** [comment]
This is being discussed in https://github.com/projectfluent/fluent/issues/150.

**Comment by stasm** [comment]
As per the decision in https://github.com/projectfluent/fluent/issues/150, we won't need this for now. Closing the PR. Thanks, @zbraniecki, for submitting it in the first place.

**Pull request closed without merging**
