### PR TITLE
Bug 922577 - Do not leak attributes between translations

### PR DESCRIPTION
**Pull request by stasm**
https://bugzilla.mozilla.org/show_bug.cgi?id=922577

### CODE REVIEW

**Comment by zbraniecki** [comment]
If I understand the patch correctly, you'd like to forbid localizable attributes to be placed in the source.
It seems like it could surprise a developer - maybe we should log a warning if that happens?

**Comment by stasm** [comment]
> If I understand the patch correctly, you'd like to forbid localizable attributes to be placed in the source.

I think there are a few things we could do to improve the developer experience:
  - warn when a non-localizable element is present in source (it will be removed),
  - warn when a localizable attribute is removed from the source element,
  - warn when a localizable attribute us removed from a source element's child.

Do you think we should do all of them in this PR?

**Comment by zbraniecki** [comment]
Maybe we should even start with throwing?

**Comment by stasm** [comment]
I think throwing is only a viable option for the first use-case from my comment above. In the other two we could break the UI on retranslation if the new localization is missing an attribute.

**Pull request merged**
