### PR TITLE
Add node 10 to test matrix

### PR DESCRIPTION
**Pull request by Pike**

### CODE REVIEW

**Comment by Pike** [comment]
Resurrecting old branches ...

This breaks because node 10 has `Intl`, but doesn't ship any ICU data.

I guess there are two ways to fix this, one is to figure out how to get ICU data into the node 10 tests, the other would be to skip the test that checks the polyfill. Condition could be `new Intl.PluralRules('pl').resolvedOptions().locale !== 'pl'`

@stasm ?

**Comment by stasm** [comment]
For option 1, there's https://nodejs.org/api/intl.html#intl_providing_icu_data_at_runtime and https://www.npmjs.com/package/full-icu.

**Comment by Pike** [comment]
Yeah, that's what I found as well. What I haven't found is how to hook that up to travis.

**Comment by stasm** [comment]
We should look at the larger picture: `fluent-intl-polyfill` is going away (#293). I wouldn't bother about fixing this test; let's just remove the test (we can rely on the [upstream tests](https://github.com/eemeli/intl-pluralrules/blob/master/src/plural-rules.test.js) instead), or fix #293 first.

**Comment by stasm** [comment]
I'd like to add node 9, 11, and 12 to the matrix, too, while we're at it.

**Comment by stasm** [comment]
Or, actually, let's stick to the even numbers. 8, 10, and 12.

**Comment by eemeli** [comment]
At least for Intl.PluralRules, the `intl-pluralrules` polyfill [will verify](https://github.com/eemeli/intl-pluralrules/blob/30b37fce4621a1ce1865d1d4a0e2d1cf5ca98300/src/polyfill.js#L16) that that an existing implementation actually works for multiple locales. But that's obviously not the only Intl object that Fluent cares about.

**Comment by Pike** [comment]
@stasm might know why we're using a fork of an old version of `intl-pluralrules` ;-)

**Comment by stasm** [comment]
Because I didn't have time to fix #293 yet :) Any takers?

**Pull request merged**
